company_name_mapping = {
    "mcd": "Mc Donald's",
    "amz": "Amazon",
    "ubr": "Uber",
    "msft": "Microsoft",
    "goog": "Google",
    "fb": "Facebook",
    "apl": "Apple",
    "tsla": "Tesla",
    "ibm": "IBM",
    "csc": "CSC Corporation",
    "hp": "Hewlett-Packard",
    "intc": "Intel Corporation",
    "csco": "Cisco Systems",
    "orcl": "Oracle Corporation",
    "qcom": "Qualcomm",
    "ebay": "eBay",
    "yhoo": "Yahoo",
    "nflx": "Netflix",
    "sbux": "Starbucks",
    "bkng": "Booking Holdings",
    "baba": "Alibaba Group",
    "adbe": "Adobe Systems",
    "crm": "Salesforce.com",
    "nvda": "NVIDIA",
    "pypl": "PayPal",
    "cmcsa": "Comcast",
    "pfe": "Pfizer",
    "jnj": "Johnson & Johnson",
    "wmt": "Walmart",
    "vz": "Verizon Communications",
    "xom": "Exxon Mobil",
    "ba": "Boeing",
    "pg": "Procter & Gamble",
    "ko": "Coca-Cola",
    "pep": "PepsiCo",
    "mcd": "McDonald's",
    "dis": "Walt Disney",
    "nke": "Nike"
}
